#!/usr/bin/env python3
import sys
import lisp
import editor


def main():
    args = sys.argv[1:]
    interpreter = lisp.LispInterpreter()
    repl = editor.Editor(interpreter)
    repl.run()


if __name__ == "__main__":
    main()
