#!/usr/bin/env python3
import sys
import lisp
import editor


def main():
    args = sys.argv[1:]
    interpreter = lisp.TinyLispInterpreter()
    repl = editor.Editor(interpreter, prelude_filenames=["samples/church.lisp"])
    repl.run()


if __name__ == "__main__":
    main()
